### PR TITLE
Started on Complex Class

### PR DESCRIPTION
**Pull request by mightymatias**
Only thing left to be done is to add the logic for mathematical operations. I'll leave that for you @KarltonSen . Let me know if this looks good for you and I'll merge it to master.

### CODE REVIEW

**Comment by scday** [comment]
I forgot to add the math formulas. I'm going back to do that now. I like how you are working together! What happened to @uncg-csc230-2019-classroom-1/codereddead the rest of the team? Tyrell and Rohan?

**Comment by KarltonSen** [comment]
They haven’t joined yet

**Comment by scday** [comment]
Ok. I have also updated the readme.md file on the course website: https://github.com/uncg-csc230-2019-classroom-1 . Make sure to encourage your classmates. Reach out to them. Communication is something that we all responsible for.

**Comment by scday** [comment]
Keep up the great work too!

**Comment by scday** [comment]
@KarltonSen @mightymatias Would you be willing to demonstrate to your peers on Wednesday?

**Comment by KarltonSen** [comment]
I will and thank you for the update to the module

**Comment by KarltonSen** [comment]
I wouldn’t mind.

**Comment by scday** [comment]
You're welcome @KarltonSen ! Is this difficult working together via GitHub? Are you all using the command prompt/terminal or a desktop client? @mightymatias

**Comment by KarltonSen** [comment]
We are using the desktop app to do this work

**Comment by scday** [comment]
Nice!

**Comment by KarltonSen** [comment]
I did not see the updated Read Me file

**Comment by scday** [comment]
@KarltonSen Did you got to the classroom and then week 7 in-class activity?

**Comment by KarltonSen** [comment]
Yes I think I did

**Comment by scday** [comment]
https://github.com/uncg-csc230-2019-classroom-1/Week-7-In-Class-Activity @KarltonSen

**Comment by KarltonSen** [comment]
Thanks.

**Comment by scday** [comment]
you're welcome

**Pull request merged**
